language: java
sudo: false
install: true


addons:
  sonarcloud:
    organization: "wz2cool-github" # the key of the org you chose at step #3
    token:
      secure: "Zd5JBJiCw7OrIgZz5bBw7gc2Konte7ZrjmsYcF8O/uGktDSMI9vIW1eVwYpb9GbOpou+OyvAvyMP5yFhbzcjtXDrylxqO+Kywl145CAuq6M00ITf00kajWTuNYWfhI41izV22oaFHDjf1xoWpH9EME7+bZjYWNrN6F+Y8eMoYw/ur+8dyKlcZDuDgSw6feBsl6Ii017neiuU1JGoSbS/HuWox6h+tGB3u2avjNgkVaTRwhoqIloP27ljfDMI9holzAD5n6lJycQsslkwkzlSawo/9I0G7a/Womjf+p3MjJmCdyQAsjh0YA7saPDxoxa21nrj2wQ8VpVqqRB1PX0w1gcznLDwGKa0KZmL9sjXSLYJhZDx9a9n819vF9b+uzSyxYsIcBhP9xtxzgYb+K8kkuG/jKNOsPl9n/KD8ccBWB9P1gIN9aKy88VTeTG5Y0u0cvDfWG4VMwZEmJXmQaOPwOaMSOFtpyYgngBITgYDDQ1kZbOiGEV9Afx+MJmFm12vC+kQUd9krXI3lpWUMqx/Rz6WsB0IiJq13C8tctPIaZckhrzpYc2QcC4F4Bcfk7En8LDOb33f0pEFPPErLvlKGBplGgTiOkLuaI2nMlZuqSShhsFQJJY/TRUWUkqTA9nhB7xM3jtbTdURO9sVY7gByDl6iRAPeUm9SjXoKtaA9+A=" # encrypted value of your token
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

after_success:
  - mvn clean test jacoco:report coveralls:report

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

jdk:
  - oraclejdk8
